# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-python/pytest-runner/pytest-runner-1.1.ebuild,v 1.3 2014/08/10 21:18:23 slyfox Exp $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

EAPI=4
#RESTRICT_PYTHON_ABIS="3.*"

inherit distutils eutils

MY_PN=${PN#python-}
S="${WORKDIR}/${MY_PN}-${PV}"
DESCRIPTION="Adds support for tests durring installation of setup.py files"
HOMEPAGE="http://pypi.python.org/pypi/pytest-runner"
SRC_URI="mirror://pypi/p/${MY_PN}/${MY_PN}-${PV}.zip"
LICENSE="MIT"
KEYWORDS="~amd64 ~x86"
SLOT="0"
IUSE=""
DEPEND="dev-python/hgtools
		dev-python/setuptools"
RDEPEND="dev-python/pytest"

src_prepare() {
	epatch "${FILESDIR}/pytest-runner.patch"
}

src_install() {
	distutils_src_install
}
