language: python
python:
  - 2.7

env:
  - JOB=global
  - JOB=0
  - JOB=1
  - JOB=2
  - JOB=3
  - JOB=4
  - JOB=5
  - JOB=6
  - JOB=7

install:
  - wget -O - "https://github.com/gentoo/travis-repo-checks/archive/master.tar.gz" | tar -xz
  - bash travis-repo-checks-master/prepare-tests.bash

script:
  - bash travis-repo-checks-master/run-tests.bash ${JOB} 8
