# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-perl/Term-Shell/Term-Shell-0.20.0.ebuild,v 1.1 2011/08/28 14:24:59 tove Exp $
# This ebuild generated by g-cpan 0.16.0

EAPI=4

MODULE_AUTHOR=NEILW
MODULE_VERSION=0.02
inherit perl-module

DESCRIPTION="A simple command-line shell framework"

SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""
