#!/sbin/runscript
# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/mail-mta/opensmtpd/files/smtpd.initd,v 1.1 2013/02/28 17:57:15 zx2c4 Exp $

depend() {
	need net
}

start() {
	ebegin "Starting OpenSMTPD"
	start-stop-daemon --start --quiet --exec /usr/sbin/smtpd
	eend ${?}
}

stop() {
	ebegin "Stopping OpenSMTPD"
	/usr/sbin/smtpctl stop
	eend ${?}
}
