# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-haskell/abstract-deque/abstract-deque-0.3.ebuild,v 1.2 2014/07/25 09:16:40 slyfox Exp $

EAPI=5

# ebuild generated by hackport 0.3.6.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Abstract, parameterized interface to mutable Deques"
HOMEPAGE="https://github.com/rrnewton/haskell-lockfree/wiki"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE="usecas"

RDEPEND="dev-haskell/random:=[profile?]
	>=dev-lang/ghc-6.12.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8.0.2
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag usecas usecas)
}
