# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-python/keyring/keyring-1.0.ebuild,v 1.3 2013/01/01 00:30:29 prometheanfire Exp $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

EAPI=5
PYTHON_COMPAT=( python2_5 python2_6 python2_7 )

inherit distutils-r1 eutils

MY_PN=${PN#python-}
S="${WORKDIR}/${MY_PN}-${PV}"
DESCRIPTION="Provides a easy way to access the system keyring service from
python."
HOMEPAGE="https://bitbucket.org/kang/python-keyring-lib"
SRC_URI="mirror://pypi/k/${MY_PN}/${MY_PN}-${PV}.zip"
LICENSE="PSF-2"
KEYWORDS="~amd64 ~x86"
SLOT="0"
IUSE="test"
DEPEND="dev-python/setuptools[${PYTHON_USEDEP}]
		test? ( dev-python/pytest
				dev-python/pytest-runner
				dev-python/unittest2 )"
RDEPEND=""
PATCHES=( "${FILESDIR}/setup-1.0.patch" )

python_test() {
	"${PYTHON}" keyring/tests/test_util.py || die
	"${PYTHON}" keyring/tests/test_backend.py || die
	"${PYTHON}" keyring/tests/test_core.py || die
	"${PYTHON}" keyring/tests/test_cli.py || die
}
