# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-python/plyr/plyr-1.0.2.ebuild,v 1.1 2014/06/22 12:28:01 idella4 Exp $
# Ebuild generated by g-pypi 0.3

EAPI="5"
PYTHON_COMPAT=( python{2_7,3_3,3_4} )

inherit distutils-r1 flag-o-matic

DESCRIPTION="A python wrapper for Glyr"
HOMEPAGE="http://sahib.github.com/python-glyr/intro.html"
SRC_URI="mirror://pypi/p/plyr/${P}.tar.gz"

LICENSE="GPL-3+"
KEYWORDS="~amd64"
SLOT="0"

RDEPEND="media-libs/glyr"
DEPEND="${RDEPEND}
		dev-python/cython[${PYTHON_USEDEP}]
		dev-python/setuptools[${PYTHON_USEDEP}]"

python_compile() {
	if ! python_is_python3; then
		local CFLAGS=${CFLAGS}
		append-cflags -fno-strict-aliasing
	fi
	distutils-r1_python_compile
}
