#!/sbin/runscript
# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:

name="OpenVAS Scanner"
command="/usr/sbin/openvassd"
command_args="${SCANNER_LISTEN} ${SCANNER_PORT} ${SCANNER_SRCIP} ${SCANNER_EXTRA_ARGS}"
pidfile="/run/openvassd.pid"

depend() {
	after bootmisc
	need localmount net
}

start_pre() {
	checkpath --directory --mode 0775 --quiet /var/cache/openvas
}
