#!/sbin/runscript
# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/app-emulation/cloud-init/files/cloud-config.init,v 1.1 2014/03/16 21:05:12 prometheanfire Exp $

depend() {
    after cloud-init-local
    after cloud-init
    before cloud-final
    provide cloud-config
}

start() {
    cloud-init modules --mode config
    eend 0
}
