#!/sbin/runscript
# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/app-emulation/cloud-init/files/cloud-init.init,v 1.1 2014/03/16 21:05:12 prometheanfire Exp $

# add depends for network, dns, fs etc
depend() {
    after cloud-init-local
    before cloud-config
    provide cloud-init
}

start() {
    cloud-init init
    eend 0
}
