# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/sci-mathematics/agda-lib-ffi/agda-lib-ffi-0.0.2.ebuild,v 1.2 2014/08/10 20:23:23 slyfox Exp $

EAPI=5

# ebuild generated by hackport 0.3.5

CABAL_FEATURES="lib"
inherit haskell-cabal

AGDA_P="lib-0.7"

DESCRIPTION="Auxiliary Haskell code used by Agda's standard library"
HOMEPAGE="http://wiki.portal.chalmers.se/agda/"
SRC_URI="http://www.cse.chalmers.se/~nad/software/${AGDA_P}.tar.gz"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-lang/ghc-6.10.4:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.8
"

S="${WORKDIR}/${AGDA_P}/ffi"

src_prepare() {
	cabal_chdeps \
		'base >= 3.0.3.1 && < 4.7' 'base >= 3.0.3.1 && < 4.8'
}
