#!/sbin/runscript
# Copyright 1999-2006 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/app-admin/syslogread/files/0.92/syslogread.init,v 1.1 2006/06/11 11:52:56 bangert Exp $

opts="depend start stop"

depend() {
	need svscan
	provide logger
}

start() {
	ebegin "Starting logger"
	true
	eend $? "Failed to start logger"
}

stop() {
	ebegin "Stopping logger"
	true
	eend $? "Failed to stop logger"
}
