--- plan-1.9/src/Makefile.orig	2008-03-19 03:38:22.000000000 -0500
+++ plan-1.9/src/Makefile	2008-03-19 03:42:49.000000000 -0500
@@ -415,10 +415,10 @@
 	env CF="$(SVR4_C)" L1F="$(SVR4_L1)" L2F="$(SVR4_L2)" MYCC=gcc make all
 
 linux:
-	env CF="$(LINUX_C)" L1F="$(LINUX_L1)" L2F="$(LINUX_L2)" MYCC=gcc make all
+	env CF="$(LINUX_C)" L1F="$(LINUX_L1)" L2F="$(LINUX_L2)" MYCC=${CC} make all
 
 slinux:
-	env CF="$(LINUX_C)" L1F="$(SLINUX_L1)" L2F="$(SLINUX_L2)" MYCC=gcc make all
+	env CF="$(LINUX_C)" L1F="$(SLINUX_L1)" L2F="$(SLINUX_L2)" MYCC=${CC} make all
 
 news4:
 	make CF="$(NEWS_C)" L1F="$(NEWS_L1)" L2F="$(NEWS_L2)" MYCC=cc all
