# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-python/async/async-0.6.1.ebuild,v 1.2 2011/08/27 20:55:38 neurogeek Exp $
# Ebuild generated by g-pypi 0.1

EAPI="3"
PYTHON_DEPEND="2"
SUPPORT_PYTHON_ABIS="1"
#Tests fail randomly for Python2.7
#DISTUTILS_SRC_TEST="nosetests"

inherit eutils distutils

DESCRIPTION="Async Framework"
HOMEPAGE="http://gitorious.org/git-python/async
	http://pypi.python.org/pypi/async"
SRC_URI="mirror://pypi/${P:0:1}/${PN}/${P}.tar.gz"

LICENSE="BSD"
KEYWORDS="~amd64 ~x86"
SLOT="0"
IUSE=""

RDEPEND="sys-libs/zlib"
DEPEND="dev-python/setuptools
		${RDEPEND}"
RESTRICT_PYTHON_ABIS="3*"

src_prepare() {
	distutils_src_prepare
	epatch "${FILESDIR}/${P}_libz_link.patch"
}
