# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-haskell/ieee754/ieee754-0.7.3-r1.ebuild,v 1.1 2013/08/25 05:15:09 qnikst Exp $

EAPI=5

# ebuild generated by hackport 0.3.1

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Utilities for dealing with IEEE floating point numbers"
HOMEPAGE="http://github.com/patperry/hs-ieee754"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-lang/ghc-6.10.4:=
		virtual/libc"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.2.0"
