#!/sbin/runscript
# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-db/mongodb/files/mongodb.initd,v 1.4 2011/08/26 12:38:49 ultrabug Exp $

depend() {
	need net
}

start() {
	mkdir -p ${MONGODB_RUN:-/var/run/mongodb}
	chown ${MONGODB_USER:-mongodb}: ${MONGODB_RUN:-/var/run/mongodb}

	# Listen to MONGODB_IP if configured
	[ -z "${MONGODB_IP}" ] || MONGODB_OPTIONS="--bind_ip ${MONGODB_IP} ${MONGODB_OPTIONS}"

	# Baselayout-1 user should use --chuid instead of --user
	local USEROPT="--user"
	if [ ! -f /etc/init.d/sysfs ]; then
		USEROPT="--chuid"
	fi

	ebegin "Starting ${SVCNAME}"
	start-stop-daemon --background --start --make-pidfile \
		--pidfile ${MONGODB_RUN:-/var/run/mongodb}/${SVCNAME}.pid \
		${USEROPT} ${MONGODB_USER:-mongodb} \
		--exec ${MONGODB_EXEC:-/usr/bin/mongod} \
		-- \
		--port ${MONGODB_PORT:-27017} \
		--dbpath ${MONGODB_DATA:-/var/lib/mongodb} \
		--unixSocketPrefix ${MONGODB_RUN:-/var/run/mongodb} \
		--logappend --logpath /var/log/mongodb/${SVCNAME}.log \
		${MONGODB_OPTIONS}
	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop --pidfile ${MONGODB_RUN:-/var/run/mongodb}/${SVCNAME}.pid
	eend $?
}
