#!/sbin/runscript
# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/dev-vcs/git/files/git-daemon-r1.initd,v 1.1 2014/02/04 09:36:35 polynomial-c Exp $

pidfile="/run/git-daemon.pid"
command="/usr/bin/git"
command_args="daemon --pid-file=${pidfile} --user=${GIT_USER} --group=${GIT_GROUP} ${GITDAEMON_OPTS}"
start_stop_daemon_args="-b -p ${pidfile}"

depend() {
	use logger
}
