#!/sbin/runscript
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/net-analyzer/sguil-sensor/files/sensor_agent.initd,v 1.4 2006/03/25 22:00:31 swegener Exp $

depend() {
        need net
}

checkconfig() {
        if [ ! -e /etc/sguil/sensor_agent.conf ] ; then
                eerror "You need an /etc/snort/sensor_agent.conf to run the Sensor Agent"
                return 1
        fi
}

start() {
        checkconfig || return 1
        ebegin "Starting Sensor Agent"
        start-stop-daemon --start -c sguil --quiet --exec /usr/bin/sensor_agent.tcl \
		-- -D -c "/etc/sguil/sensor_agent.conf">/dev/null 2>&1
        eend $?
}

stop() {
        ebegin "Stopping Sensor Agent"
        start-stop-daemon --stop --quiet --pidfile /var/run/sguil/sensor.pid
        eend $?
}

